//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NETLAP.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_NETLAPTYPE                  130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_LeftFind_Dialog             310
#define IDR_HTML_LEFTFIND               311
#define IDD_Pattern_Dialog              312
#define IDD_PatternPrint_Dialog         312
#define IDD_RightFind_Dialog            313
#define IDR_HTML_LEFTFIND1              314
#define IDR_HTML_LEFTFINDDLG            315
#define IDR_HTML_LEFTFINDDLG1           317
#define IDD_Test_DIALOG                 317
#define IDR_HTML_LEFTFINDDLG2           319
#define IDR_HTML_LEFTFINDDLG3           322
#define IDR_HTML_RIGHTFINDDLG           323
#define IDR_HTML_RIGHTFINDDLG1          325
#define IDR_HTML_TESTDLG                326
#define IDC_Minlen_TextBox              1000
#define IDC_LABEL1                      1001
#define IDC_LABEL2                      1002
#define IDC_TEXTBOX2                    1003
#define IDC_LABEL3                      1004
#define IDC_Maxlen_TextBox              1005
#define IDC_COMMANDBUTTON3              1006
#define IDC_LABEL4                      1007
#define IDC_LABEL5                      1008
#define IDC_COMMANDBUTTON4              1009
#define IDC_COMMANDBUTTON5              1010
#define IDC_LABEL6                      1011
#define IDC_LABEL7                      1012
#define IDC_Occurrence_TextBox          1014
#define IDC_Pattern_TextBox             1015
#define IDC_Minlen_Edit                 1018
#define IDC_Maxlen_Edit                 1019
#define IDC_Pattern_Edit                1020
#define IDC_Number_Edit                 1021
#define IDC_Time_Edit                   1022
#define IDC_Occurrence_Edit             1026
#define IDC_RightFind_Button            1027
#define IDC_Minlen_Edit1                1028
#define IDC_Maxlen_Edit1                1029
#define IDC_Pattern_Edit1               1030
#define IDC_Break_Button1               1031
#define IDC_Break_Button                1031
#define IDC_Time_Edit1                  1032
#define IDC_Number_Edit1                1033
#define IDC_Occurrence_Edit1            1034
#define IDC_LeftFind_Button             1035
#define IDC_Number_TextBox              1036
#define IDC_Time_TextBox                1037
#define IDC_BUTTON1                     1037
#define IDC_Pattern_Button              1037
#define IDC_BUTTON2                     1038
#define IDC_Cancel_Button               1038
#define IDC_Length_Edit                 1039
#define IDC_Length_Button               1040
#define IDC_PatternFile_Button          1041
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_Menu                         32774
#define ID_FILE_APPEND                  32775
#define ID_32777                        32777
#define ID_3277                         32778
#define ID_32781                        32781
#define ID_32782                        32782
#define ID_Open_PatternFile             32783
#define ID_Print_Pattern                32784
#define ID_ACCELERAID_FILE_APPEND       32786
#define ID_32787                        32787
#define ID_Pattern                      32789
#define ID_FILE_S                       32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           327
#endif
#endif
